# Generated by Django 5.0.6 on 2024-10-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('idestudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(blank=True, default='S/A', max_length=45)),
                ('correo', models.EmailField(max_length=45, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('asistencia', models.CharField(blank=True, max_length=20)),
                ('clases_asistidas', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(blank=True, default='S/A', max_length=45)),
                ('correo', models.EmailField(max_length=45, unique=True)),
                ('clave', models.CharField(max_length=128)),
            ],
        ),
    ]
